#!/usr/bin/env zsh
#
# Warning:
#   Please read all the scripts located in `./scripts/*` before running.
#   Each script asks you for confirmation before it does anything, but
#   reading them beforehand will mean you understand what is about to happen.
# cat /etc/shells
source ./scripts/shared/_utils.zsh

echo
echo -e "${PURPLE}Hey ${USER}, let's setup your mac...${NC}"

# Add error for non-catalina or zsh usage.
init_for_zsh

# Run through each module - will be given option to run or not.
do_action "Install brew and cask?" "music" "brew.zsh"
do_action "Install MAS?" "music" "mas.zsh"
do_action "Go through non-automated things?" "music" "manual.zsh"


# Final output (script complete)
echo
echo -e "${GREEN}- - - - - - EVERYTHING IS AWESOME! - - - - - -"
cat <<"EOF"

   _______       __
 /   ------.   / ._`_
|  /         ~--~    \
| |             __    `.____________________ _^-----^
| |  I=|=======/--\=========================| o o o |
\ |  I=|=======\__/=========================|_o_o_o_|
 \|                   /                       ~    ~
   \       .---.    .
     -----'     ~~''

------------------------------------------------
+ + + G O O D  J O B  -   R O C K  O N ! + + +
EOF
echo -e "${NC}"

# Also display a nice output of current apple system stats using archey
archey
